import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/AuthProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My app',
  description: 'Generated by create next app',
}



function RootLayout({
  children, ...rest
}: {
  children: React.ReactNode
}) {

  
  
  return (
    <html lang="en" className='bg-base-300'>
      <body className={inter.className}>
      <AuthProvider> 
      {children}
      </AuthProvider>
      </body>
    </html>
  )
}

export default RootLayout
